name: Run tests

on: [ push ]

jobs:
    quality:
        runs-on: ${{ matrix.os }}

        strategy:
            fail-fast: false
            matrix:
                os: [ ubuntu-latest ]
                php: [ 8.4, 8.3, 8.2, 8.1 ]

        name: Tests ${{ matrix.os }} - PHP ${{ matrix.php }}

        steps:
            -   name: Checkout code
                uses: actions/checkout@v3

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}

            -   name: Install
                run: composer install --no-interaction

            -   name: Execute tests
                run: vendor/bin/phpunit
