name: Run tests

on: [ push ]

jobs:
  quality:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php: [ 8.5, 8.4, 8.3, 8.2, 8.1 ]
        carbon: [ ^2.66.0, ^3.8.6 ]
        dependency-version: [ prefer-lowest, prefer-stable ]

    name: Tests PHP ${{ matrix.php }} - Carbon ${{ matrix.carbon }} - ${{ matrix.dependency-version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Install
        run: |
          composer require "nesbot/carbon:${{ matrix.carbon }}" --no-interaction --no-update
          composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction

      - name: Execute tests
        run: composer test
